site_name: 文化课攻略收集站 for 24OI

repo_name: 'Hanoist/24OI'
repo_url: 'https://github.com/Hanoist/24OI'

nav:
- 首页: 'mainpage.md'
- 更新日志: 'log.md'
- 欢迎来到不够完美的高中生活 by Hanoist: 
    - 在开始之前: 'intro.md'
    - 我写这篇文章的动机: '0.md'
    - 追赶课程进度: 
        - 整体策略: '1.md'
        - 单科学习: 
            - 数学: 'math.md' 
            - 物理: 'phi.md'
            - 化学: 'che.md'
            - 生物: 'bio.md'
            - 语文: 'chn.md'
            - 英语: 'eng.md'
        - 起步之后: '1_.md'
    - 平衡执念和现实: 
        - 沉没成本: '2.md'
        - 绝处逢生: '2_.md'
        - 和解？: '2__.md'
    - 直面高考压力: 
        - 决战之前: '3.md'
        - 能力自信: '3_.md'
        - 考试的意义: '3__.md'
    - 收尾和反思: 
        - 结束了？: '4.md'
        - 浅谈一点志愿选择: '4_.md'
    - 结尾的一点碎碎念: 'end.md'
- 学习资料 offered by 望月 Asta: 'file.md'
theme: material