site_name: 文化课攻略收集站 for 24OI

repo_name: 'Hanoist/24OI'
repo_url: 'https://github.com/Hanoist/24OI'

nav:
- 首页: 'mainpage.md'
- 更新日志: 'log.md'
- 学习资料: 'file.md'
- 欢迎来到不够完美的高中生活 by Hanoist: 
    - 在开始之前: 'hanoist/intro.md'
    - 我写这篇文章的动机: 'hanoist/0.md'
    - 追赶课程进度: 
        - 整体策略: 'hanoist/1.md'
        - 单科学习: 
            - 数学: 'hanoist/math.md' 
            - 物理: 'hanoist/phi.md'
            - 化学: 'hanoist/che.md'
            - 生物: 'hanoist/bio.md'
            - 语文: 'hanoist/chn.md'
            - 英语: 'hanoist/eng.md'
        - 起步之后: 'hanoist/1_.md'
    - 平衡执念和现实: 
        - 沉没成本: 'hanoist/2.md'
        - 绝处逢生: 'hanoist/2_.md'
        - 和解？: 'hanoist/2__.md'
    - 直面高考压力: 
        - 决战之前: 'hanoist/3.md'
        - 能力自信: 'hanoist/3_.md'
        - 考试的意义: 'hanoist/3__.md'
    - 收尾和反思: 
        - 结束了？: 'hanoist/4.md'
        - 浅谈一点志愿选择: 'hanoist/4_.md'
    - 结尾的一点碎碎念: 'hanoist/end.md'
- 寄语 : 'message.md'

theme: material