name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Generate cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Copy contribution guide
        run: cp CONTRIBUTING.md docs/contributing.md

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build index
        run: python3 -O ./gen_index.py

      - name: Build file list
        run: python3 -O ./gen_file_list.py

      - name: Generate site
        run: mkdocs gh-deploy --force